name: Test build & Scrape

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  TYPESENSE_NODE: ${{ vars.TYPESENSE_NODE }}
  TYPESENSE_ADMIN_API_KEY: ${{ secrets.TYPESENSE_ADMIN_API_KEY }}

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm i

      - name: Build website
        run: npm run build

      - name: Run DocSearch Scraper
        uses: celsiusnarhwal/typesense-scraper@v2
        with:
          # The secret containing your Typesense API key. Required.
          api-key: ${{ env.TYPESENSE_ADMIN_API_KEY }}

          # The hostname or IP address of your Typesense server. Required.
          host: ${{ env.TYPESENSE_NODE }}

          # The port on which your Typesense server is listening. Optional. Default: 8108.
          port: 443

          # The protocol to use when connecting to your Typesense server. Optional. Default: http.
          protocol: https

          # The path to your DocSearch config file. Optional. Default: docsearch.config.json.
          config: docsearch.config.json
